# Generated by Django 5.0.4 on 2024-06-09 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': [('can_create_product', 'Can create product'), ('can_view_product', 'Can view product')]},
        ),
    ]
